### ISSUE TITLE
clarification on `currentAnimationInfo` return data

### ISSUE THREAD

**Issue by kevzettler** [chinedufn/skeletal-animation-system#11]
Hi chinedfun, 

I'm confused on what `lowerKeyframeNumber` and `upperKeyframeNumber` actually represent. 

```
{
  joints: [...],
  currentAnimationInfo: {
    lowerKeyframeNumber: 0,
    upperKeyframeNumber:: 1
  }
}
```

The lower/upper distinction could mean that it's for the  lower/upper dual quaternions but following the example from the README you would call `interpolateJoints` twice giving you 2 sets of `lower/upperKeframeNumber`

```
var interpolatedUpperBodyJoints = animationSystem
.interpolateJoints(upperBodyOptions).joints
console.log(upperBodyData.currentAnimationInfo)
// => {lowerKeyframeNumber: 5, upperKeyframeNumber: 6}

var lowerBodyData = animationSystem
.interpolateJoints(lowerBodyOptions)
console.log(lowerBodyData.currentAnimationInfo)
// => {lowerKeyframeNumber: 5, upperKeyframeNumber: 6}
```

**Comment by chinedufn** [comment]
Sorry I'm not entirely following what you're asking.

It looks like in that example we're interpolating the upper body and the lower body and then printing out the `currentAnimationInfo`.

If you have three keyframes at `1` `8` and `19` seconds and you are currently `12` seconds into your animation then your lower keyframe is `1` (8) and your upper keyframe is `2` (19).

Thanks for pointing out that this is poorly communicated - how can that be made more clear?

**Comment by kevzettler** [comment]
Ok that makes sense, so its `upper` and `lower` time bounds?

I'm Not entirely sure how to better communicate it. maybe something like  `minPossibleKeyframe`, `maxPossibleKeyfram`

**Comment by chinedufn** [comment]
Yeah it's the index of the two keyframes that surround the current time.

The two keyframes that you're currently interpolating.

Maybe 

```
currentAnimationInfo: {
  surroundingKeyframeIndices: {
    lower: 5,
    upper: 6
  }
}
```

?

**Comment by kevzettler** [comment]
That would be a breaking change as it changes the return signature. I'd say maybe leave as is and add a note to the README for now

**Comment by chinedufn** [comment]
I'm actually not as concerned about breaking changes since it's `pre 1.0` so while unfortunate breaking changes are somewhat to be expected as we iterate towards a better API.

On a sort of related note... spent a few months on backend work for my game but diving back into client side now so will hopefully be using `skeletal-animation-system` in the real world and spotting more warts like this soon!

**Comment by kevzettler** [comment]
Cool excited @chinedufn excited for some updates! I just used this to add Punching animations on plebland.com

**Comment by chinedufn** [comment]
![image](https://user-images.githubusercontent.com/2099811/40656951-2209fece-6314-11e8-993e-496ff9dad2f7.png)
haha sweet I just took a look at your project and kicked server daemon's butt
