### ISSUE TITLE
cannot find module when run demo 

### ISSUE THREAD

**Issue by juicycool92** [chinedufn/skeletal-animation-system#15]
Hellothere, thanks for making awesome modules, but i got error while trying to demo.

what i did

```
$ git clone https://github.com/chinedufn/skeletal-animation-system
$ cd skeletal-animation-system
$ npm install
$ npm run demo
```
get error msg like

```
Cannot find module 'C:\Users\Jay\Desktop\prototypes\skeletons\skeletal-animation-system\demo\webgl\browser-entry.js'
skeletal-animation-system\
```

can anyone help?

Thanks

**Comment by chinedufn** [comment]
Hey!

Hmmm - looks like the demo was removed while we were moving to a new demo that never got completed.

For now you can try an older commit:

```
git clone https://github.com/chinedufn/skeletal-animation-system
git checkout 269f65f1bece6c9d98ddaf0460ad67ad356975ab
cd skeletal-animation-system
npm install
npm run demo
```

**Comment by chinedufn** [comment]
Let me know if you have any other issues!

**Comment by juicycool92** [comment]
> 
> 
> Let me know if you have any other issues!

work fantastic! thanks.
