### ISSUE TITLE
New demo code

### ISSUE THREAD

**Issue by mdkq** [chinedufn/skeletal-animation-system#9]
Hey so I've cleaned up the demo site quite a bit:

- Removed all content but demo and links
- Links now go straight to the appropriate section of the readme on github
- Cleaned up unused classes/css etc.

I was going to just copy the old demo and fit it into the new page, but I remember you (@chinedufn) saying that you were considering redoing the demo. Is that still something you want to do or is it cool if I just go ahead and try to use the old stuff?

**Comment by chinedufn** [comment]
That was more of an ~eventually type of thing - so yeah go for it!

**Comment by chinedufn** [comment]
The API has changed a little since the old demo. Namely `{currentAnimation,previousAnimation}.range` were removed in favor of `.keyframes` https://github.com/chinedufn/skeletal-animation-system#currentanimation

**Comment by mdkq** [comment]
Hey friend. Looks like I'm getting an error from the SAS code. 
<img width="730" alt="screen shot 2018-04-24 at 4 52 56 pm" src="https://user-images.githubusercontent.com/4454291/39213605-0a22f0a8-47e0-11e8-8a21-e41eccecbf93.png">

whatcha know about that?

**Comment by chinedufn** [comment]
Ah I bet it's from an API change

Needs to be `currentAnimation.keyframes` and `previousAnimation.keyframes` instead of wherever they're stored in your screenshot. example: https://github.com/chinedufn/skeletal-animation-system/#previousanimation

**Comment by mdkq** [comment]
Ok sorry to be a pest but I'm a little in over my head here. Getting this error now:

<img width="799" alt="screen shot 2018-04-27 at 11 15 55 am" src="https://user-images.githubusercontent.com/4454291/39370259-7659e690-4a0c-11e8-98d8-9cc2cc058bcd.png">

I pushed my code here (basically exactly the tutorial code AFAIK)
https://github.com/chinedufn/skeletal-animation-system/blob/demo-rework/demo/main.js

Any ideas?
